In [1]:
import os
os.getcwd()

'C:\\Users\\Stefan\\LRZ Sync+Share\\Masterarbeit-Klein\\Code\\Results'

# Usage of exponential smoothing in API

## Ziel

Hier möchte ich zeigen, dass exponential smoothing wie in Koch, 3.3. Update of parameters erwähnt, im Wesentlichen eine Durchschnittsbildung ist.

## Vorgehensweise

Den relevanten Code habe ich in der Datei "1 E_API_lin_single_leg.py" gespeichert. Hier gibt es in der Methode *update_parameters* zwei unterschiedliche return statements, einmal ohne und einmal mit exponential smoothing.

Die Ergebnisse der beiden Durchläufe habe ich gespeichert:
* 1-no-exponential-smoothing--smallTest-False-API-lin-190612-1049: ohne exponential smoothing
* 1-exponential-smoothing--smallTest-False-API-lin-190612-1055: mit exponential smoothing

Zu diesem Zeitpunkt habe ich den Algorithmus zur Approximate policy iteration (Koch Kapitel 3) für den linearen Fall (nicht piecewise) und **mit** exploration vs. exploitation dilemma implementiert. 

## verwendete Daten

Als Beispieldatensatz wurde der folgende verwendet.
data_by_name["smallTest"] = {}

data_by_name["smallTest"]["products"] = np.arange(4)  # n
data_by_name["smallTest"]["revenues"] = np.array([1000, 800, 600, 400])

data_by_name["smallTest"]["times"] = np.arange(10)  # T

data_by_name["smallTest"]["customer_segments"] = np.arange(1)  # L
data_by_name["smallTest"]["arrival_probabilities"] = np.array([0.5])
data_by_name["smallTest"]["preference_weights"] = np.array([[0.4, 0.8, 1.2, 1.6]])

data_by_name["smallTest"]["var_no_purchase_preferences"] = np.array([[1]])
data_by_name["smallTest"]["preference_no_purchase"] = \
    np.array(data_by_name["smallTest"]["var_no_purchase_preferences"][0])

data_by_name["smallTest"]["resources"] = np.arange(1)  # m

data_by_name["smallTest"]["var_capacities"] = np.array([[4]])
data_by_name["smallTest"]["capacities"] = data_by_name["smallTest"]["var_capacities"][0]

\# capacity demand matrix A (rows: resources, cols: products)
\# a_ij = 1 if resource i is used by product j
data_by_name["smallTest"]["A"] = np.array([[1, 1, 1, 1]])


Und für die Policy Iteration:
K = 10
I = 100

In [2]:
import pandas as pd
import numpy as np

import pickle
import copy

In [4]:
with open(r"C:\Users\Stefan\LRZ Sync+Share\Masterarbeit-Klein\Code\Results\2-no-exponential-smoothing--smallTest-False-API-lin-190613-0949\thetaAll.data", "rb") as f:
    thetas_no_es = pickle.load(f)
with open(r"C:\Users\Stefan\LRZ Sync+Share\Masterarbeit-Klein\Code\Results\2-no-exponential-smoothing--smallTest-False-API-lin-190613-0949\piAll.data", "rb") as f:
    pis_no_es = pickle.load(f)
    
thetas_calculated = copy.deepcopy(thetas_no_es)
for k in np.arange(len(thetas_no_es)-1)+1:
    thetas_calculated[k] = np.average(thetas_no_es[1:(k+1)], axis=0)

pis_calculated = copy.deepcopy(pis_no_es)
for k in np.arange(len(pis_no_es)-1)+1:
    pis_calculated[k] = np.average(pis_no_es[1:(k+1)], axis=0)

In [3]:
with open(r"C:\Users\Stefan\LRZ Sync+Share\Masterarbeit-Klein\Code\Results\2-exponential-smoothing--smallTest-False-API-lin-190613-0947\thetaAll.data", "rb") as f:
    thetas_es = pickle.load(f)
with open(r"C:\Users\Stefan\LRZ Sync+Share\Masterarbeit-Klein\Code\Results\2-exponential-smoothing--smallTest-False-API-lin-190613-0947\piAll.data", "rb") as f:
    pis_es = pickle.load(f)

In [6]:
thetas_no_es - thetas_es

array([[[   0.        ],
        [   0.        ],
        [   0.        ],
        [   0.        ],
        [   0.        ],
        [   0.        ],
        [   0.        ],
        [   0.        ],
        [   0.        ],
        [   0.        ]],

       [[   0.        ],
        [   0.        ],
        [   0.        ],
        [   0.        ],
        [   0.        ],
        [   0.        ],
        [   0.        ],
        [   0.        ],
        [   0.        ],
        [   0.        ]],

       [[  33.41349604],
        [   5.74797303],
        [ -24.18106137],
        [ -22.20351939],
        [ -24.39916453],
        [ -41.58152098],
        [ -46.60779668],
        [ -40.33509247],
        [ -36.37532444],
        [ -23.44931082]],

       [[  -9.68892031],
        [  -1.21399838],
        [ -33.34853493],
        [  -9.73674948],
        [ -13.64905831],
        [ -21.77421394],
        [ -33.04231241],
        [ -16.30948928],
        [   6.4618674 ],
        [  -3.37988

In [5]:
thetas_calculated - thetas_es

array([[[ 0.00000000e+00],
        [ 0.00000000e+00],
        [ 0.00000000e+00],
        [ 0.00000000e+00],
        [ 0.00000000e+00],
        [ 0.00000000e+00],
        [ 0.00000000e+00],
        [ 0.00000000e+00],
        [ 0.00000000e+00],
        [ 0.00000000e+00]],

       [[ 0.00000000e+00],
        [ 0.00000000e+00],
        [ 0.00000000e+00],
        [ 0.00000000e+00],
        [ 0.00000000e+00],
        [ 0.00000000e+00],
        [ 0.00000000e+00],
        [ 0.00000000e+00],
        [ 0.00000000e+00],
        [ 0.00000000e+00]],

       [[ 0.00000000e+00],
        [ 0.00000000e+00],
        [ 0.00000000e+00],
        [ 0.00000000e+00],
        [ 0.00000000e+00],
        [ 0.00000000e+00],
        [ 0.00000000e+00],
        [ 0.00000000e+00],
        [ 0.00000000e+00],
        [ 0.00000000e+00]],

       [[-4.54747351e-13],
        [-2.27373675e-13],
        [ 0.00000000e+00],
        [-2.27373675e-13],
        [ 0.00000000e+00],
        [-1.13686838e-13],
        [ 0.00000000e+

In [7]:
pis_calculated - pis_es

array([[[ 0.00000000e+00],
        [ 0.00000000e+00],
        [ 0.00000000e+00],
        [ 0.00000000e+00],
        [ 0.00000000e+00],
        [ 0.00000000e+00],
        [ 0.00000000e+00],
        [ 0.00000000e+00],
        [ 0.00000000e+00],
        [ 0.00000000e+00]],

       [[ 0.00000000e+00],
        [ 0.00000000e+00],
        [ 0.00000000e+00],
        [ 0.00000000e+00],
        [ 0.00000000e+00],
        [ 0.00000000e+00],
        [ 0.00000000e+00],
        [ 0.00000000e+00],
        [ 0.00000000e+00],
        [ 0.00000000e+00]],

       [[ 0.00000000e+00],
        [ 0.00000000e+00],
        [ 0.00000000e+00],
        [ 0.00000000e+00],
        [ 0.00000000e+00],
        [ 0.00000000e+00],
        [ 0.00000000e+00],
        [ 0.00000000e+00],
        [ 0.00000000e+00],
        [ 0.00000000e+00]],

       [[ 0.00000000e+00],
        [-5.68434189e-14],
        [ 2.84217094e-14],
        [-2.84217094e-14],
        [ 0.00000000e+00],
        [-1.42108547e-14],
        [ 0.00000000e+